name: finbert
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21,<1.25
  - pandas=1.5.3
  - nltk=3.9.1
  - tqdm=4.64.0
  - ipykernel=6.29.5
  - matplotlib
  - pytorch=2.0.1
  - torchvision
  - torchaudio
  - notebook
  - jupyterlab
  - jupyter_client
  - pip
  - pip:
      - transformers==4.40.1
      - joblib==1.4.2
      - scikit-learn==1.1.3
      - spacy==3.7.5
      - textblob==0.15.3